language: ruby
services: mongodb

notifications:
  email: false

rvm:
  - 2.3.3
  - 2.5.0

env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

  - "UPLOADS=paperclip"
  - "UPLOADS=carrierwave"
  - "RAILS=1 UPLOADS=paperclip"
  - "RAILS=1 UPLOADS=carrierwave"

gemfile:
  - gemfiles/mongoid-6.0.gemfile
  - gemfiles/mongoid-6.3.gemfile

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
