language: ruby
services: mongodb

notifications:
  email: false

rvm:
  - 2.3.3
  - 2.5.0

env:
  global:
    - CC_TEST_REPORTER_ID=f23ba257d0a12c588551991b4377e3eb218c1ff80050bc48c6b18c49ca16cb62
  matrix:
    - "UPLOADS=paperclip"
    - "UPLOADS=carrierwave"
    - "UPLOADS=shrine"
    - "RAILS=1 UPLOADS=paperclip"
    - "RAILS=1 UPLOADS=carrierwave"
    - "RAILS=1 UPLOADS=shrine"

gemfile:
  - gemfiles/mongoid-6.0.gemfile
  - gemfiles/mongoid-6.3.gemfile

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
