language: ruby
services: mongodb

notifications:
  email: false

rvm:
  - 2.3.3
  - 2.5.0

env:
  - "UPLOADS=paperclip"
  - "UPLOADS=carrierwave"
  - "RAILS=1 UPLOADS=paperclip"
  - "RAILS=1 UPLOADS=carrierwave"

gemfile:
  - gemfiles/mongoid-6.0.gemfile
  - gemfiles/mongoid-6.3.gemfile

